name: Test

on: 
  workflow_dispatch:

jobs:
  Palladio-Core-Commons:
    needs: []
    if: success() || failure()
    uses: PalladioSimulator/Palladio-Build-ActionsPipeline/.github/workflows/build.yml@skipAndUpdate
    with:
      use-display-output: true
      build-repository: PalladioSimulator/Palladio-Core-Commons
      deploy-updatesite: 'releng/org.palladiosimulator.core-commons.updatesite/target/repository'
    secrets:
      SERVER_SSH_KEY: empty
      REMOTE_HOST: empty
      REMOTE_PORT: 22
      REMOTE_USER: empty
      REMOTE_TARGET: empty